### ISSUE TITLE
Handle rate limits

### ISSUE THREAD

**Issue by ChrisTorresLugo** [osome-iu/osometweet#1]
The headers returned by each API call contain the following fields:

> - x-rate-limit-limit: the rate limit ceiling for that given endpoint
> - x-rate-limit-remaining: the number of requests left for the 15-minute window
> - x-rate-limit-reset: the remaining window before the rate limit resets, in UTC epoch seconds

These fields are documented [here](https://developer.twitter.com/en/docs/twitter-api/rate-limits). Method calls should parse these fields to determine when to sleep the process and for how long. Performing additional requests when the limit has been reached risks account suspension.

**Comment by mr-devs** [comment]
Has anyone thought about the best way to handle this?

I was thinking that we could convert everything below [this line in the _user_lookup method](https://github.com/osome-iu/osometweet/blob/02c86035cc030a6bc79f6d6e8111a2ed53ccd5ec/osometweet/api.py#L311) into a function and then add a boolean argument to each method called `wait` (or whatever) which, when `True`, calls that function.

I think that it would mostly just be adding a single if-conditional in each internal/base method and then deciding where we want to put the new function.

Thoughts?

**Comment by mr-devs** [comment]
On second thought, this might be better to include within the `oauth.py` file?

**Comment by mr-devs** [comment]
See #54.

**Comment by mr-devs** [comment]
There may be some room for improvement, however, this is functionally addressed at the moment so I'm going to close. Please create new issues for improvements.
