### ISSUE TITLE
Document the exsiting methods and utils

### ISSUE THREAD

**Issue by yangkcatiu** [osome-iu/osometweet#11]
To make it easier to use for other people (e.g., other group members), let's put some documentations in the readme file.

- [x] create a new documentation branch
- [x] document the initialization of `OsomeTweet` class, especially about the two different oauth methods
- [x] document tweet lookup
- [x] document user lookup ids and usernames
- [x] document utils.pause_until
- [x] document utils.chunker

**Comment by mr-devs** [comment]
I will work on:
* The initialization of `OsomeTweet` 
    * Authorization and authorization control
* User lookup ids and usernames
* All of the utils methods (pause_until, chunker, ObjectFields)

**Comment by yangkcatiu** [comment]
The docs seem to cover everything now. I'll close this issue. For new methods/classes, we will create issues for them later.
