### ISSUE TITLE
Develop friends/followers methods

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#16]
I will probably need to figure this out for the retweet cascade reconstruction part of the superspreaders project so I will have to look into this anyway. If anyone else wants to dig into this, please feel free to assign yourself and go for it because I probably won't get to this for a couple of weeks. 

I liked the structural approach that Kaicheng took in his edits to the user lookup methods - having one base method and two user-facing methods (one for IDs and one for usernames) that feed into the base method - so I will try and do the same thing.

Please add any other thoughts you may have. 

---
* [Reference](https://developer.twitter.com/en/docs/twitter-api/users/follows/migrate)

- [X] Base Method
- [X] Friends Method
- [X] Followers Method
- [x] Update README.md

**Comment by yangkcatiu** [comment]
We also need to update the readme for the new methods.

**Comment by mr-devs** [comment]
Thanks again for building the base method. I'll work on the documentation stuff right now.

**Comment by mr-devs** [comment]
Closing this despite the fact that pagination methods are still missing because it's covered in #29.
