### ISSUE TITLE
Decouple osometweet and OAuth

### ISSUE THREAD

**Issue by yangkcatiu** [osome-iu/osometweet#19]
It's probably time to extract the OAuth part out of the osometweet class.

**Comment by yangkcatiu** [comment]
TODO:

- [ ] Create an Oauth class
- [ ] Extract Oauth related stuffs from OsomeTweet class
- [ ] Create tests for the Oauth class
- [ ] Add documentations for the Oauth class

**Comment by mr-devs** [comment]
@yangkcatiu I am closing this because it seems like the last bullet point has been addressed in the `README.md`. If you had something else in mind, please feel free to reopen.
