### ISSUE TITLE
Lists as input for the set_x_fields methods?

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#22]
Right now all of the setting methods (`set_place_fields`, `set_polls_fields`, etc.) all take a string. What do we think about changing this to take a list of strings? We can handle the "stringification" within the method easily with a join. This seems more straight forward and less likely to lead to errors, IMO. 

For example, we are assuming that people are going to build the url string correctly, but maybe it's best to do this for them to ensure it's correct?

If you guys are okay with this, I am happy to make these changes and can take care of #12 at the same time.

**Comment by yangkcatiu** [comment]
Lists seem to be better!

**Comment by mr-devs** [comment]
Closing this because we are phasing these methods out. See #28 for the new approach.
