### ISSUE TITLE
Doc-string format

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#26]
Is there a reason to utilize this docstring format...
```
:param [str, list, tuple] tids
:returns requests.models.Response
:raises Exception, ValueError
```
vs. this one?
```
Parameters:
    - tids [str, list, tuple] - twitter id numbers
Returns:
    - requests.models.Response
Raises:
    - Exception, ValueError
```

The latter is, IMO, much more readable but I've seen the first a lot and I wasn't sure if there are any functional differences?

**Comment by yangkcatiu** [comment]
There was no particular reason. But we can use the second one as the standard.

**Comment by yangkcatiu** [comment]
See #27

**Comment by mr-devs** [comment]
this has been merged. Thanks, Kaicheng!
