### ISSUE TITLE
Handle Endpoint Argument Options

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#28]
I originally suggested adding `**kwargs` for all methods in #23 because I thought that there would be too many options. Looking at the endpoints, I actually think it's easier to just include all options explicitly.

Below is a list of endpoint methods and their available options.

### Tweet Lookup
- [x]  `tweet_lookup`
    - [x] `ids`
    - [x] `expansions`
        - [x] attachments.poll_ids
        - [x] attachments.media_keys
        - [x] author_id
        - [x] entities.mentions.username
        - [x] geo.place_id
        - [x] in_reply_to_user_id
        - [x] referenced_tweets.id
        - [x] referenced_tweets.id.author_id
    - [x] `media.fields`
    - [x] `place.fields`
    - [x] `poll.fields`
    - [x] `tweet.fields`
    - [x] `user.fields`
- [x] Update Doc strings
- [x] Update Tests

### User Lookup IDs
- [ ]  `user_lookup_ids`
    - [x] `ids`
    - [x] `expansions`
        - [ ] pinned_tweet_id
    - [x] `tweet.fields`
    - [x] `user.fields`
- [ ] Update Doc strings
- [ ] Update Tests

### User Lookup Usernames
- [ ]  `user_lookup_usernames`
    - [x] `usernames`
    - [ ] `expansions`
        - [ ] pinned_tweet_id
    - [ ] `tweet.fields`
    - [ ] `user.fields`
- [ ] Update Doc strings
- [ ] Update Tests

### Get Followers
- [ ]  `get_followers`
    - [x] `id`
    - [ ] `expansions`
        - [ ] pinned_tweet_id
    - [ ] `max_results`
    - [ ] `pagination_token`
    - [ ] `tweet.fields`
    - [ ] `user.fields`
- [ ] Update Doc strings
- [ ] Update Tests

### Get Following
- [ ]  `get_following`
    - [x] `id`
    - [ ] `expansions`
        - [ ] pinned_tweet_id
    - [ ] `max_results`
    - [ ] `pagination_token`
    - [ ] `tweet.fields`
    - [ ] `user.fields`
- [ ] Update Doc strings
- [ ] Update Tests

### Remove
- [ ] `set_user_fields`
- [ ] `set_tweets_fields`
- [ ] `set_poll_fields`
- [ ] `set_place_fields`
- [ ] `set_media_fields`

**Comment by mr-devs** [comment]
I've been working on the tweet_lookup method and will submit a PR soon

**Comment by mr-devs** [comment]
`tweet_lookup` addressed in PR #29.

**Comment by yangkcatiu** [comment]
Please see #32

**Comment by mr-devs** [comment]
Closing, the new structure should allow us to handle all of these.
