### ISSUE TITLE
Include an "everything" option within each method option

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#31]
For example, if we want to use the `tweet_lookup()` method. 

You could do something like the following:
```python
resp = self.ot.tweet_lookup(
    tids = random_tweet_id,
    everything = True
    )
```
And this would be equivalent to including all `expansions`, `tweet.fields`, `place.fields`, `poll.fields`, `tweet.fields`, and `user.fields`.

> Another option would be to include and `all` option for _each_ data object, however, since we have the `return_objectfield()` methods, I think this might be overkill. It's really easy to just call `t_fields = o_utils.return_tweet_fields()` and then place `t_fields` in the `ot.tweet_lookup()` call. As a result, I think it's best to build out the first option.

--- 
### Methods
- [x] `tweet_lookup`
- [x] `user_lookup_ids`
- [x] `user_lookup_usernames`
- [x] `get_followers`
- [x] `get_following`

**Comment by yangkcatiu** [comment]
Please see #32

**Comment by mr-devs** [comment]
Thank you, Kaicheng.
