### ISSUE TITLE
get_all_avail_fields() not working for user_lookup_ids()

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#40]
Here is the code and error I got:

```python
>>> import osometweet
>>> import os
>>> bearer_token = os.environ.get("TWITTER_BEARER_TOKEN")
>>> all_fields = osometweet.fields.get_all_avail_fields()
>>> expansions = osometweet.UserExpansions()
>>> oauth2 = osometweet.OAuth2(bearer_token=bearer_token)
>>> ot = osometweet.OsomeTweet(oauth2)
>>> ot.user_lookup_ids('12', fields=all_fields, expansions=expansions)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthewdeverna/Documents/GitHub/osometweet/osometweet/api.py", line 216, in user_lookup_ids
    return self._user_lookup(user_ids, "id", fields=fields, expansions=expansions)
  File "/Users/matthewdeverna/Documents/GitHub/osometweet/osometweet/api.py", line 289, in _user_lookup
    "Invalid parameter type: `query` must be" "either a list or tuple."
ValueError: Invalid parameter type: `query` must beeither a list or tuple.
```

**Comment by mr-devs** [comment]
I should note:
1. The above approach using `osometweet.fields.get_all_avail_fields()` does work for the `tweet_lookup` endpoint.
2. The `user_lookup_ids` endpoint works fine if you utilize `fields.UserFields(everything = True)` to get the full list.

**Comment by yangkcatiu** [comment]
I'll look into this.

**Comment by yangkcatiu** [comment]
The error above can be fixed by `ot.user_lookup_ids(['12'])`.

But you are right, `get_all_avail_fields()` doesn't work with `user_lookup_ids()`. This is because the user endpoints only accept user and tweet fields. `get_all_avail_fields()` returns media, place, and poll fields as well. I'm trying to think how to solve this issue elegantly. Might need to adjust the code structure a little bit.

**Comment by mr-devs** [comment]
Makes sense. I'm not sure what the best solution is either.

It seems like this could be an annoyance for future endpoints or others we haven't fully tested yet. I am thinking there are two approaches, generally:
1. We could check the fields provided and automatically strip out only the fields accepted for each endpoint prior to the query - perhaps an internal `utils.py` function  `_strip_fields()`?
2. Remove the `get_all_avail_fields()` method and let the users use the individual fields classes with the `everything = True` option (i.e. `UserFields(everything=True)`)

I'm almost leaning towards 2, even though the `get_all_avail_fields()` method is quite nice because I think it could be a headache to manage it down the road. However, I am okay with whatever you decide.

**Comment by yangkcatiu** [comment]
I came up with a solution in #44 . The nice thing about is that now we can simply use `ot. user_lookup_ids(['12'], everything=True)` to get all the fields and expansions, and the `everything` parameter works for all the endpoints.

The not so nice thing about it is that we have to update the documents and examples accordingly.

**Comment by mr-devs** [comment]
No worries. I think it's a great improvement. 

Closing. See #46 to track updates.
