### ISSUE TITLE
Add twitter-api-v2 as repo topic?

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#43]
What do we think about adding the [twitter-api-v2](https://github.com/topics/twitter-api-v2) topic to the repo?

I think this can only be done by an admin. Based on [these instructions](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics), the gear icon is not there to allow me to do this - not sure @yangkcatiu if you are an admin?

**Comment by ChrisTorresLugo** [comment]
Sure, it'll give the repo more visibility.

**Comment by mr-devs** [comment]
Agreed. Some other topic ideas taken from the Tweepy repo: `python` `twitter` `twitter-api`

**Comment by yangkcatiu** [comment]
Agreed. Didn't know this thing before.

**Comment by mr-devs** [comment]
Awesome. @yangkcatiu do you know who the admin is? I think that they need to do this for us.

**Comment by yangkcatiu** [comment]
@johnbryden could you take a look of this?

**Comment by mr-devs** [comment]
@johnbryden, pinging you for this again. Is this something you can take care of or do we need someone else to do it?

Just so everything is in one place, we'd like to add the following repo topics:
- python
- twitter
- twitter-api
- twitter-api-v2

**Comment by mr-devs** [comment]
thanks john!
