### ISSUE TITLE
Historical Search Endpoint

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#51]
Please claim if you think you can get to this. 

- [x] API functionality
- [x] Add documentation
- [x] Add tests

**Comment by mr-devs** [comment]
I need to look into this for the superspreaders project this week so I'll claim this. Please let me know if anyone has any thoughts about the best way to implement this.

**Comment by yangkcatiu** [comment]
Probably not until next week. Got some deadlines.

**Comment by mr-devs** [comment]
No worries! Good luck with everything.

**Comment by mr-devs** [comment]
See #53.
