### ISSUE TITLE
Samples Stream Endpoint

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#52]
Please claim if you think you can get to this. 

- [ ] API functionality
- [ ] Add documentation
- [ ] Add tests

**Comment by ChrisTorresLugo** [comment]
I have the API functionality working, will have a PR by tomorrow covering everything on the checklist. Then I'll move to filter as it should be a modification of this endpoint.

**Comment by mr-devs** [comment]
awesome, thanks!
