### ISSUE TITLE
Generalize make_request

### ISSUE THREAD

**Issue by ChrisTorresLugo** [osome-iu/osometweet#61]
Currently, OAuth{1,2}'s make_request uses requests.get() to contact the API. The filtered stream endpoint requires the use of POST to establish the rules that the stream will be filtered on. Other endpoints in the future might require POST or other methods. To get around this issue, I'll be changing make_requests to use requests.requests(method={"GET", "POST",etc}) and will update all the endpoints to pass the corresponding method to make_request.

**Comment by mr-devs** [comment]
awesome, thanks Chris!

**Comment by mr-devs** [comment]
Addressed in #74.
