### ISSUE TITLE
Functions for data cleaning

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#70]
I think it would be good to build out functions for cleaning the data that `osometweet` returns. 

I was watching one of the Twitter Twitch sessions about doing this and they shared [this module from twarc](https://github.com/DocNow/twarc/blob/v2/twarc/expansions.py) which can be used to partially flatten the data JSON to create a data frame for a csv file. I don't think we can directly take this and work it into our package, however, I thought it could be good to reference. 

I'm thinking that this would require it's own module, maybe called `wrangle` or `data`? Open to suggestions. I'm thinking of functions like:
- `wrangle.extract()` which takes an input of a raw tweet dict and then "text", "urls", "hashtags", etc.
- `wrangle.flatten()` which takes a single raw tweet dict and returns it in row form
- etc.

**Comment by mr-devs** [comment]
#76 starts to do build this out.

If you have other ideas, please drop them in this issue. Thanks!

**Comment by mr-devs** [comment]
Dropping this collection of ["getter" methods](https://github.com/twitterdev/tweet_parser/tree/master/tweet_parser/getter_methods) here from the twitter_dev `tweet_parser` package. Could be nice to build something like this into our package but definitely is not necessary.

**Comment by yangkcatiu** [comment]
I guess we can close this now.
