### ISSUE TITLE
Automatic linting check

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#78]
In an effort to tighten up the last bit of code I'd like to take the lead on going through everything with [`pylint`](https://pylint.org/). Right now, we get a pretty bad score almost entirely due to long lines in the docstrings (my bad 😉 - I've made some changes in my editor which should keep this from happening in the future) but there are some other small things that can be addressed as well.

If no one has any objections, I am going to go through all of the code and tighten things up based on `pylint`'s recommendations. (BTW, please let me know if you do have an issue with this for some reason and/or you recommend something else!)

However, I was wondering... is there a way to build this type of check into our tests pre-merge? If this is a lot of work, I'm not sure it will be worth it but, if it's easy, I think it could be nice to set up. For example, I think there is a way to get GitHub to block merges unless it passes a `pylint` check, however, I don't know what is involved to get this done.

Please let me know your thoughts when you can.

**Comment by yangkcatiu** [comment]
Sounds good. I'm using VScode which has some extensions that would automatically formats the code upon saving. You can try things like this if it sounds helpful.

**Comment by mr-devs** [comment]
Yeah I'm going to close this for now and we'll just deal with it individually. I don't think it needs to be perfect...
