### ISSUE TITLE
Do the filtered streaming rules reset?

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/osometweet#85]
Need to figure out whether the filtered streaming rules persist forever, or they reset at some point.

I opened a question on [twittercommunity.com](https://twittercommunity.com/t/how-long-do-filtered-streaming-rules-last/158486) asking exactly this but please do chime in if you've found an answer somewhere.

**Comment by yangkcatiu** [comment]
Thank you for posting the question! My guess is that Twitter won't reset the rules automatically, but it would be nice if we can get response from them.

**Comment by mr-devs** [comment]
Agreed. I'll update the issue once I hear back from them on twittercommunity.

**Comment by mr-devs** [comment]
Closing this because we got a [response](https://twittercommunity.com/t/how-long-do-filtered-streaming-rules-last/158486/2?u=mdeverna2) from Igor Brigadir who is working with some Twitter developers to create `twarc`...

> No official docs or word on it but I’ve had rules sit there for like a month or so and reconnecting the stream worked again. So I would say they’re permanent.
